// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Wedding.Wishlist.DataAccess.Data.Contexts;

#nullable disable

namespace Wedding.Wishlist.DataAccess.Migrations
{
    [DbContext(typeof(WeddingWishlistDbContext))]
    [Migration("20260105175617_Users")]
    partial class Users
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            base.BuildTargetModel(modelBuilder);
        }
    }
}
